import Head from "next/head";

import { NextPageWithLayout } from "@/utils/types";
import { Main } from "@/components/atoms/Main";
import { GetServerSideProps } from "next";
import LoginForm from "@/components/organisms/LoginForm/LoginForm";
import { ChangeEvent, useContext, useEffect, useState } from "react";
import { useRouter } from "next/router";
import { Title } from "@/components/atoms/Titles";
import { AuthContext } from "@/context/authContext";
import axios from "axios";

interface Props {
  users: any;
}

const LoginPage: NextPageWithLayout<Props> = ({ users }) => {
  const [username, setUsername] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const ctx = useContext(AuthContext)
  const router = useRouter();

  useEffect(() => {
    if (ctx.userName !== "") router.push("/admin/dashboard");
  }, [ctx.userName, router])

  const onSubmit = (): void => {
    axios.post('/api/auth/login', {
      username,
      password
    }).then((res: any) => {
      if (res.data.success) {
        ctx.login(res.data.username)
      } else {
        alert("Gagal Login")
      }
    })
  };

  const handleusernameChange = (e: ChangeEvent<HTMLInputElement>): void => {
    setUsername(e.target.value);
  };

  const handlePasswordChange = (e: ChangeEvent<HTMLInputElement>): void => {
    setPassword(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by Doorprize" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main className="bg-secondaryAdmin h-screen w-screen flex justify-center flex-col items-center">
        <Title className="text-white">Login</Title>
        <LoginForm
          onSubmit={onSubmit}
          onUsernameChange={handleusernameChange}
          onPasswordChange={handlePasswordChange}
        />
      </Main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {},
  };
};

export default LoginPage;
