import Head from "next/head";

import { NextPageWithLayout } from "@/utils/types";
import { AdminTemplate } from "@/components/templates/AdminTemplate";
import { Main } from "@/components/atoms/Main";
import { GetServerSideProps } from "next";
import useUsers from "@/hooks/useUsers";
import LoginForm from "@/components/organisms/LoginForm/LoginForm";
import { Typography } from "antd";
import { auth, logInWithEmailAndPassword } from "@/firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import { ChangeEvent, use, useState } from "react";
import { useRouter } from "next/router";
import { Title } from "@/components/atoms/Titles";

interface Props {
  users: any;
}

const LoginPage: NextPageWithLayout<Props> = ({ users }) => {
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [user, loading, error] = useAuthState(auth);
  const router = useRouter();

  if (loading) {
    return (
      <Typography.Title className="flex-center" style={{ height: "80vh" }}>
        Loading...
      </Typography.Title>
    );
  }

  if (user) router.push("/admin/dashboard");

  const onSubmit = (): void => {
    logInWithEmailAndPassword(email, password);
  };

  const handleEmailChange = (e: ChangeEvent<HTMLInputElement>): void => {
    setEmail(e.target.value);
  };

  const handlePasswordChange = (e: ChangeEvent<HTMLInputElement>): void => {
    setPassword(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by Doorprize" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main className="bg-secondaryAdmin h-screen w-screen flex justify-center flex-col items-center">
        <Title className="text-white">Login</Title>
        <LoginForm
          onSubmit={onSubmit}
          onEmailChange={handleEmailChange}
          onPasswordChange={handlePasswordChange}
        />
      </Main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {},
  };
};

export default LoginPage;
