import Head from "next/head";

import { NextPageWithLayout } from "@/utils/types";
import { AdminTemplate } from "@/components/templates/AdminTemplate";
import { TitleAdminPage } from "@/components/molecules/TitleAdminPage";
import { Main } from "@/components/atoms/Main";
import { Background } from "@/components/organisms/AdminList";
import { GetServerSideProps } from "next";

const DoorprizePage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Doorprize</title>
        <meta name="description" content="Generated by Doorprize" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <TitleAdminPage placeHolder="Doorprize /" title="Background Sesi" />
        <Background />
      </Main>
    </>
  );
};

DoorprizePage.getLayout = page => {
  return (
    <>
      <AdminTemplate>{page}</AdminTemplate>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {},
  };
};

export default DoorprizePage;
