import Head from "next/head";

import { NextPageWithLayout } from "@/utils/types";
import { AdminTemplate } from "@/components/templates/AdminTemplate";
import { TitleAdminPage } from "@/components/molecules/TitleAdminPage";
import { Main } from "@/components/atoms/Main";
import { SessionList } from "@/components/organisms/AdminList";
import { GetServerSideProps } from "next";
import sql from "@/utils/db";

interface Props {
  sessions: any[];
}

const DoorprizePage: NextPageWithLayout<Props> = ({ sessions }) => {  
  return (
    <>
      <Head>
        <title>Doorprize</title>
        <meta name="description" content="Generated by Doorprize" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <TitleAdminPage title="Doorprize" />
        <SessionList sessions={sessions} />
      </Main>
    </>
  );
};

DoorprizePage.getLayout = page => {
  return (
    <>
      <AdminTemplate>{page}</AdminTemplate>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  // const sessions = [
  //   {
  //     id_session: 1,
  //     nama_session: "Sesi 1",
  //   },
  //   {
  //     id_session: 2,
  //     nama_session: "Sesi 2",
  //   },
  //   {
  //     id_session: 3,
  //     nama_session: "Sesi 3",
  //   },
  // ];

  const sessions = await sql("SELECT * FROM sessions").then((res: any) => res.map((sess: any) => {
    return {
      id_session: sess?.id_session,
      nama_session: sess?.nama_session
    }
  }))
  
  return {
    props: {
      sessions,
    },
  };
};

export default DoorprizePage;
