import Head from "next/head";

import { NextPageWithLayout } from "@/utils/types";
import { AdminTemplate } from "@/components/templates/AdminTemplate";
import { TitleAdminPage } from "@/components/molecules/TitleAdminPage";
import { AdminDashboardCardList } from "@/components/organisms/AdminDashboardCardList";
import { DashboardList } from "@/components/organisms/AdminList";
import { Main } from "@/components/atoms/Main";

const DashboardAdminPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by Doorprize" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <TitleAdminPage title="Dashboard" />
        <AdminDashboardCardList />
        <DashboardList />
      </Main>
    </>
  );
};

DashboardAdminPage.getLayout = page => {
  return (
    <>
      <AdminTemplate>{page}</AdminTemplate>
    </>
  );
};

export default DashboardAdminPage;
