import Head from "next/head";

import { NextPageWithLayout } from "@/utils/types";
import { AdminTemplate } from "@/components/templates/AdminTemplate";
import { TitleAdminPage } from "@/components/molecules/TitleAdminPage";
import { AdminDashboardCardList } from "@/components/organisms/AdminDashboardCardList";
import { DashboardList } from "@/components/organisms/AdminList";
import { Main } from "@/components/atoms/Main";
import { GetServerSideProps } from "next";
import useWinner from "@/hooks/useWinner";
import sql from "@/utils/db";

interface Props {
  winner: any;
  jumlahUser: number;
  jumlahBlacklistUser: number;
  jumlahDoorprize: number;
}

const DashboardAdminPage: NextPageWithLayout<Props> = ({
  winner,
  jumlahBlacklistUser,
  jumlahDoorprize,
  jumlahUser,
}) => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by Doorprize" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <TitleAdminPage title="Dashboard" />
        <AdminDashboardCardList
          jumlahPemenang={winner?.length}
          jumlahBlacklistUser={jumlahBlacklistUser}
          jumlahDoorprize={jumlahDoorprize}
          jumlahUser={jumlahUser}
        />
        <DashboardList winner={winner} />
      </Main>
    </>
  );
};

DashboardAdminPage.getLayout = page => {
  return (
    <>
      <AdminTemplate>{page}</AdminTemplate>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  // const winner = [
  //   {
  //     id_user: 1,
  //     nama_user: "Faizah Masturina Yuatno 1",
  //     no_hp: "087858881307",
  //     domisili: "Depok Lama",
  //     status: "active",
  //     nama_hadiah: "Sepeda JBL",
  //     gambar: "sepedaJBL.jpg",
  //   },
  //   {
  //     id_user: 2,
  //     nama_user: "Faizah Masturina Yuatno 2",
  //     no_hp: "087858881307",
  //     domisili: "Depok Baru",
  //     status: "blacklist",
  //     nama_hadiah: "Sepeda JBL",
  //     gambar: "sepedaJBL.jpg",
  //   },
  //   {
  //     id_user: 3,
  //     nama_user: "Faizah Masturina Yuatno 3",
  //     no_hp: "087858881307",
  //     domisili: "Depok Modern",
  //     status: "active",
  //     nama_hadiah: "Sepeda JBL",
  //     gambar: "sepedaJBL.jpg",
  //   },
  // ];

  const winner = await sql(
    " SELECT users.id_user, users.nama_user, users.no_hp, users.domisili, users.status, prize.nama_prize, prize.nama_gambar FROM winner INNER JOIN users ON  users.id_user=winner.id_user INNER JOIN prize ON prize.id_prize=winner.id_prize"
  ).then((res: any) => {
    return res.map((win: any) => ({
      id_user: win?.id_user,
      nama_user: win?.nama_user,
      no_hp: win?.no_hp,
      domisili: win?.domisili,
      status: win?.status,
      nama_prize: win?.nama_prize,
      nama_gambar: win?.nama_gambar
    }))
  })

  const jumlahUser = await sql(
    "SELECT COUNT(id_user) as count from users where status='active'",
  ).then((res: any) => res[0].count);
  const jumlahBlacklistUser = await sql(
    "SELECT COUNT(id_user) as count from users where status='blacklist'",
  ).then((res: any) => res[0].count);
  const jumlahDoorprize = await sql(
    "SELECT COUNT(id_prize) as count from prize",
  ).then((res: any) => res[0].count);

  return {
    props: {
      winner,
      jumlahUser,
      jumlahBlacklistUser,
      jumlahDoorprize,
    },
  };
};

export default DashboardAdminPage;
