import { NextPage } from "next";
import Head from "next/head";

const DoorprizePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Doorprize</title>
        <meta name="description" content="Generated by Doorprize" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}


export default DoorprizePage